blank_issues_enabled: false
contact_links:
  - name: ❓ Support & Discussion
    url: https://gitter.im/asaskevich/godi
    about: 'You can leave comments and participate in the discussion via Gitter:'
